package scan

import (
	"reflect"
	"testing"

	"zu/internal/ir"
)

func TestBuildDeclNodes(t *testing.T) {
	doc := scanTree(t, map[string]string{
		"go.mod": "module example.com/m\n",
		"p/a.go": `package p

type Repo struct{}

func (r *Repo) Get() {}

func New() {}

func init() {}

func init() {}
`,
	})
	yes, no := true, false
	_ = no
	want := map[string]ir.Node{
		"example.com/m/p.Repo":     {ID: "example.com/m/p.Repo", Kind: ir.KindType, Parent: "example.com/m/p", Exported: &yes, TypeKind: ir.TypeStruct, Locations: []ir.Location{{Path: "p/a.go", Line: 3}}},
		"example.com/m/p.Repo.Get": {ID: "example.com/m/p.Repo.Get", Kind: ir.KindFunction, Parent: "example.com/m/p.Repo", Exported: &yes, Locations: []ir.Location{{Path: "p/a.go", Line: 5}}},
		"example.com/m/p.New":      {ID: "example.com/m/p.New", Kind: ir.KindFunction, Parent: "example.com/m/p", Exported: &yes, Locations: []ir.Location{{Path: "p/a.go", Line: 7}}},
		"example.com/m/p.init":     {ID: "example.com/m/p.init", Kind: ir.KindFunction, Parent: "example.com/m/p", Exported: &no, Locations: []ir.Location{{Path: "p/a.go", Line: 9}, {Path: "p/a.go", Line: 11}}},
	}
	for id, w := range want {
		n := node(doc, id)
		if n == nil {
			t.Fatalf("missing node %s", id)
		}
		if len(n.Hash) != 64 {
			t.Errorf("%s: hash %q", id, n.Hash)
		}
		got := *n
		got.Hash = ""
		if !reflect.DeepEqual(got, w) {
			t.Errorf("%s\n got %+v\nwant %+v", id, got, w)
		}
	}
	pkg := node(doc, "example.com/m/p")
	if pkg == nil || len(pkg.Hash) != 64 || pkg.Parent != "" || pkg.Exported != nil {
		t.Fatalf("package node = %+v", pkg)
	}
}

func TestBuildMergesBuildVariants(t *testing.T) {
	linux := "// Code generated by x. DO NOT EDIT.\n\npackage p\n\ntype T struct{}\n\nfunc F() int { return 1 }\n"
	windows := "package p\n\ntype T int\n\nfunc F() int { return 2 }\n"
	files := map[string]string{"go.mod": "module example.com/m\n", "p/f_linux.go": linux, "p/f_windows.go": windows}
	doc := scanTree(t, files)

	f := node(doc, "example.com/m/p.F")
	if f == nil || !reflect.DeepEqual(f.Locations, []ir.Location{{Path: "p/f_linux.go", Line: 7}, {Path: "p/f_windows.go", Line: 5}}) {
		t.Fatalf("F = %+v", f)
	}
	root := tree(t, files)
	h1 := extractFile(root, "p/f_linux.go").Decls[1].Hash
	h2 := extractFile(root, "p/f_windows.go").Decls[1].Hash
	if want := hashBytes([]byte(h1 + "\n" + h2 + "\n")); f.Hash != want {
		t.Errorf("merged hash = %s, want SHA-256 over location-ordered hashes %s", f.Hash, want)
	}
	if f.Generated {
		t.Error("merged node is generated only if every declaration is")
	}
	if typ := node(doc, "example.com/m/p.T"); typ == nil || typ.TypeKind != ir.TypeOther {
		t.Fatalf("T = %+v, want typeKind other on disagreement", typ)
	}

	both := scanTree(t, map[string]string{"go.mod": "module example.com/m\n", "p/g.go": linux})
	if n := node(both, "example.com/m/p.F"); n == nil || !n.Generated || n.Hash != h1 {
		t.Fatalf("single generated declaration = %+v, want generated with its own hash", n)
	}
}

func TestBuildPackageHash(t *testing.T) {
	pkgHash := func(src string) string {
		doc := scanTree(t, map[string]string{"go.mod": "module example.com/m\n", "p/p.go": src})
		return node(doc, "example.com/m/p").Hash
	}
	base := pkgHash("package p\n\nconst C = 1\n\nfunc F() {}\n")
	if base != pkgHash("// Package p.\npackage p\n\n// C.\nconst C = 1 // one\n\n// F.\nfunc F() {}\n") {
		t.Error("comments must not change the package hash")
	}
	if base == pkgHash("package p\n\nconst C = 2\n\nfunc F() {}\n") {
		t.Error("a const change must change the package hash")
	}
	if base == pkgHash("package p\n\nconst C = 1\n\nfunc F() { panic(1) }\n") {
		t.Error("a function change must change the package hash")
	}
}

func TestBuildPackageLocatedAtFirstFile(t *testing.T) {
	doc := scanTree(t, map[string]string{
		"go.mod": "module example.com/m\n",
		"p/b.go": "package p\n",
		"p/a.go": "// doc\n\npackage p\n",
		"p/0.go": "//go:build ignore\n\npackage main\n",
	})
	pkg := node(doc, "example.com/m/p")
	if !reflect.DeepEqual(pkg.Locations, []ir.Location{{Path: "p/a.go", Line: 3}}) {
		t.Fatalf("package locations = %+v", pkg.Locations)
	}
}

func TestBuildPackageHashWithDottedImportPath(t *testing.T) {
	pkgHash := func(body string) string {
		doc := scanTree(t, map[string]string{"go.mod": "module gopkg.in/yaml.v3\n", "y.go": "package yaml\n\ntype T struct{}\n\nfunc (T) M() {" + body + "}\n"})
		n := node(doc, "gopkg.in/yaml.v3.T.M")
		if n == nil || n.Parent != "gopkg.in/yaml.v3.T" {
			t.Fatalf("method node = %+v", n)
		}
		return node(doc, "gopkg.in/yaml.v3").Hash
	}
	if pkgHash("") == pkgHash("panic(1)") {
		t.Fatal("a method change must change the package hash for a dotted import path")
	}
}
