package scan

import (
	"strings"
	"testing"
)

func extractOne(t *testing.T, src string) *fileFacts {
	t.Helper()
	root := tree(t, map[string]string{"p/f.go": src})
	return extractFile(root, "p/f.go")
}

func TestExtractBuildIgnore(t *testing.T) {
	cases := map[string]bool{
		"//go:build ignore\n\npackage p\n":           true,
		"//go:build ignore && linux\n\npackage p\n":  true,
		"//go:build linux\n\npackage p\n":            false,
		"//go:build !windows\n\npackage p\n":         false,
		"//go:build !ignore\n\npackage p\n":          false,
		"package p\n\n//go:build ignore\n":           false,
		"// Copyright\n\n//go:build ignore\n\npackage p\n": true,
	}
	for src, skip := range cases {
		if got := extractOne(t, src).Skip; got != skip {
			t.Errorf("Skip = %v, want %v for\n%s", got, skip, src)
		}
	}
}

func TestExtractGenerated(t *testing.T) {
	cases := map[string]bool{
		"// Code generated by stringer. DO NOT EDIT.\n\npackage p\n":                          true,
		"// Copyright 2026 X.\n// Licensed.\n\n// Code generated by tool. DO NOT EDIT.\n\npackage p\n": true,
		"package p\n\n// Code generated by tool. DO NOT EDIT.\n":                              false,
		"// Code generated by tool. Do not edit.\npackage p\n":                                false,
		"package p\n": false,
	}
	for src, gen := range cases {
		if got := extractOne(t, src).Generated; got != gen {
			t.Errorf("Generated = %v, want %v for\n%s", got, gen, src)
		}
	}
}

func TestExtractPackageClause(t *testing.T) {
	f := extractOne(t, "// doc\n\npackage store\n")
	if f.Err != nil {
		t.Fatal(f.Err)
	}
	if f.PkgName != "store" || f.PkgLine != 3 {
		t.Fatalf("got %q line %d", f.PkgName, f.PkgLine)
	}
}

func TestExtractParseErrorUsesRelativePath(t *testing.T) {
	root := tree(t, map[string]string{"p/bad.go": "package p\n\nfunc {\n"})
	f := extractFile(root, "p/bad.go")
	if f.Err == nil {
		t.Fatal("want parse error")
	}
	if f.Err.Path != "p/bad.go" || !strings.HasPrefix(f.Err.Message, "p/bad.go:") || strings.Contains(f.Err.Message, root) {
		t.Fatalf("Err = %+v", f.Err)
	}
	if len(f.Decls) != 0 {
		t.Fatal("a file with a parse error contributes no facts")
	}
}

func TestExtractUnreadableFile(t *testing.T) {
	root := tree(t, map[string]string{})
	f := extractFile(root, "p/missing.go")
	if f.Err == nil || strings.Contains(f.Err.Message, root) {
		t.Fatalf("Err = %+v", f.Err)
	}
}
