// Copyright 2026 The Shop Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by stringer. DO NOT EDIT.

package store

// Status is an order status.
type Status int

func (s Status) String() string { return "status" }
